import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
  // next-env.d.ts is generated by Next on every build and is gitignored.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
];

export default config;
